### ISSUE TITLE
Consider using spread syntax

### ISSUE THREAD

**Issue by Jatidude** [philipstanislaus/performant-array-to-tree#5]
Currently your implementation places all of the data from the nodes inside a "data" field. Have you considered instead using the spread syntax to maintain the structure of the data being put into trees and simply placing the new children array alongside them? I don't know what kind of performance overhead this would entail just wondering if this was a conscious choice.

**Comment by philipstanislaus** [comment]
@Jatidude good question.

The data key is just used since that was required in my initial usecase. There might be a small performance hit when using the spread syntax, but I‘d not be too concerned about that. 

Happy to merge a PR if you want to add an option to spread the data in the nodes itself. That should be an opt-in feature not to break any of the existing users‘ code bases.

**Comment by philipstanislaus** [comment]
That's great, thanks! I've left a few comments in #6

**Comment by philipstanislaus** [comment]
Merged and released as v1.2.0
